#!/command/with-contenv sh
# shellcheck shell=sh
set -eu

case "${RDP_ENABLE:-1}" in
    1|true|TRUE|True|yes|YES|Yes) ;;
    *) exec sleep infinity ;;
esac

rdp_port="${RDP_PORT:-3389}"

exec s6-setuidgid xrdp /usr/sbin/xrdp --nodaemon --port "${rdp_port}"
